### ISSUE TITLE
Build failure on unstable: cannot stat modules/.

### ISSUE THREAD

**Issue by Random-Scientist** [KaylorBen/nixcord#208]
```nix
error: Cannot build '/nix/store/yfhbxhw3k8vvmj9lsfy5pqxfdkzzbsqi-discord-0.0.390.drv'.
       Reason: builder failed with exit code 1.
       Output paths:
         /nix/store/kx7c259hdp735dc68ci0bbs7nv2k8jam-discord-0.0.390
       Last 8 log lines:
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > no configure script, doing nothing
       > Running phase: buildPhase
       > no Makefile or custom buildPhase, doing nothing
       > Running phase: installPhase
       > cp: cannot stat 'modules/.': No such file or directory
```
seems to have been introduced by 34135f3223f3ea65d2fe5eaab83bcae35ae4c4ee.

**Comment by Random-Scientist** [comment]
Looks like a typo

**Comment by 4evy** [comment]
Ah, thanks for catching this! It should be fixed by: https://github.com/FlameFlag/nixcord/commit/e8018eb324ead1179dd2760be191c460d2a4fc69

Sorry for this, I'm currently busy with IRL stuff so it's a bit hard to keep up with everything, let me know if this fixes it (or not)

**Comment by Random-Scientist** [comment]
Now there seems to be a codesigning issue ("app is damaged and can't be opened")

**Comment by 4evy** [comment]
@Random-Scientist Sometimes macOS is very annoying... Please give https://github.com/FlameFlag/nixcord/commit/f8df8ca94ae64f1678d6546355a18a9e090e7a40 a try (latest commit as of writing this) and let me know if it works, I tried on my end and it all seems fine

**Comment by Random-Scientist** [comment]
new and exciting failure. the app launches but hangs (on latest commit as of now)
```
[OpenAsar > Modules] Checking
(node:93552) UnhandledPromiseRejectionWarning: Error: Cannot find module 'discord_desktop_core'
Require stack:
- /nix/store/19y1mwvh9ch4vngjwk8xgbfba5mfapdw-discord-0.0.390/Applications/Discord.app/Contents/Resources/_app.asar/bootstrap.js
- /nix/store/19y1mwvh9ch4vngjwk8xgbfba5mfapdw-discord-0.0.390/Applications/Discord.app/Contents/Resources/_app.asar/index.js
- /nix/store/wpbjirrgxrlhrhqp8v270ad4kzb2bypi-vencord-1.14.13/patcher.js
- /nix/store/19y1mwvh9ch4vngjwk8xgbfba5mfapdw-discord-0.0.390/Applications/Discord.app/Contents/Resources/_app.asar/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1390:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:129714)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1032:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1037:22)
    at Module._load (node:internal/modules/cjs/loader:1199:37)
    at c._load (node:electron/js2c/node_init:2:17993)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:244:24)
    at Module.require (node:internal/modules/cjs/loader:1470:12)
    at require (node:internal/modules/helpers:147:16)
    at emitUnhandledRejectionWarning (node:internal/process/promises:301:15)
    at warnWithErrorCodeUnhandledRejectionsMode (node:internal/process/promises:409:5)
    at processPromiseRejections (node:internal/process/promises:475:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:106:32)
(node:93552) Error: Cannot find module 'discord_desktop_core'
Require stack:
- /nix/store/19y1mwvh9ch4vngjwk8xgbfba5mfapdw-discord-0.0.390/Applications/Discord.app/Contents/Resources/_app.asar/bootstrap.js
- /nix/store/19y1mwvh9ch4vngjwk8xgbfba5mfapdw-discord-0.0.390/Applications/Discord.app/Contents/Resources/_app.asar/index.js
- /nix/store/wpbjirrgxrlhrhqp8v270ad4kzb2bypi-vencord-1.14.13/patcher.js
- /nix/store/19y1mwvh9ch4vngjwk8xgbfba5mfapdw-discord-0.0.390/Applications/Discord.app/Contents/Resources/_app.asar/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1390:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:129714)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1032:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1037:22)
    at Module._load (node:internal/modules/cjs/loader:1199:37)
    at c._load (node:electron/js2c/node_init:2:17993)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:244:24)
    at Module.require (node:internal/modules/cjs/loader:1470:12)
    at require (node:internal/modules/helpers:147:16)
```

**Comment by 4evy** [comment]
@Random-Scientist  please try the latest commit

**Comment by Random-Scientist** [comment]
New issue, window opens but has no content, log:
```
discord_intents setup failed with error:  Error: Cannot find module '/Users/agon/Library/Application Support/discord/module_data/discord_intents'
Require stack:
- /Users/agon/Applications/Discord.app/Contents/Resources/modules/discord_desktop_core/core.asar/bundle.js
- /Users/agon/Applications/Discord.app/Contents/Resources/modules/discord_desktop_core/index.js
- /Users/agon/Applications/Discord.app/Contents/Resources/_app.asar/bootstrap.js
- /Users/agon/Applications/Discord.app/Contents/Resources/_app.asar/index.js
- /nix/store/wpbjirrgxrlhrhqp8v270ad4kzb2bypi-vencord-1.14.13/patcher.js
- /Users/agon/Applications/Discord.app/Contents/Resources/_app.asar/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1390:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:129714)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1032:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1037:22)
    at Module._load (node:internal/modules/cjs/loader:1199:37)
    at c._load (node:electron/js2c/node_init:2:17993)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:244:24)
    at Module.require (node:internal/modules/cjs/loader:1470:12)
    at require (node:internal/modules/helpers:147:16) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/agon/Applications/Discord.app/Contents/Resources/modules/discord_desktop_core/core.asar/bundle.js',
    '/Users/agon/Applications/Discord.app/Contents/Resources/modules/discord_desktop_core/index.js',
    '/Users/agon/Applications/Discord.app/Contents/Resources/_app.asar/bootstrap.js',
    '/Users/agon/Applications/Discord.app/Contents/Resources/_app.asar/index.js',
    '/nix/store/wpbjirrgxrlhrhqp8v270ad4kzb2bypi-vencord-1.14.13/patcher.js',
    '/Users/agon/Applications/Discord.app/Contents/Resources/_app.asar/index.js',
    undefined
  ]
}
discord_notifications setup failed with error:  Error: Cannot find module '/Users/agon/Library/Application Support/discord/module_data/discord_notifications'
Require stack:
- /Users/agon/Applications/Discord.app/Contents/Resources/modules/discord_desktop_core/core.asar/bundle.js
- /Users/agon/Applications/Discord.app/Contents/Resources/modules/discord_desktop_core/index.js
- /Users/agon/Applications/Discord.app/Contents/Resources/_app.asar/bootstrap.js
- /Users/agon/Applications/Discord.app/Contents/Resources/_app.asar/index.js
- /nix/store/wpbjirrgxrlhrhqp8v270ad4kzb2bypi-vencord-1.14.13/patcher.js
- /Users/agon/Applications/Discord.app/Contents/Resources/_app.asar/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1390:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:129714)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1032:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1037:22)
    at Module._load (node:internal/modules/cjs/loader:1199:37)
    at c._load (node:electron/js2c/node_init:2:17993)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:244:24)
    at Module.require (node:internal/modules/cjs/loader:1470:12)
    at require (node:internal/modules/helpers:147:16) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/agon/Applications/Discord.app/Contents/Resources/modules/discord_desktop_core/core.asar/bundle.js',
    '/Users/agon/Applications/Discord.app/Contents/Resources/modules/discord_desktop_core/index.js',
    '/Users/agon/Applications/Discord.app/Contents/Resources/_app.asar/bootstrap.js',
    '/Users/agon/Applications/Discord.app/Contents/Resources/_app.asar/index.js',
    '/nix/store/wpbjirrgxrlhrhqp8v270ad4kzb2bypi-vencord-1.14.13/patcher.js',
    '/Users/agon/Applications/Discord.app/Contents/Resources/_app.asar/index.js',
    undefined
  ]
}
Optional module ./ElectronTestRpc was not included.
Clearing GPU cache...
Clearing code cache...
Failed to write renderer settings Error: EACCES: permission denied, open '/Users/agon/Library/Application Support/Vencord/settings/settings.json'
    at writeFileSync (node:fs:2425:20)
    at file:///VencordPatcher:5:4473
    at file:///VencordPatcher:5:3339
    at Set.forEach (<anonymous>)
    at ye.markAsChanged (file:///VencordPatcher:5:3328)
    at ye.setData (file:///VencordPatcher:5:2713)
    at file:///VencordPatcher:5:4686
    at Session.<anonymous> (node:electron/js2c/browser_init:2:107040)
    at Session.emit (node:events:519:28) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/agon/Library/Application Support/Vencord/settings/settings.json'
}
Failed to write renderer settings Error: EACCES: permission denied, open '/Users/agon/Library/Application Support/Vencord/settings/settings.json'
    at writeFileSync (node:fs:2425:20)
    at file:///VencordPatcher:5:4473
    at file:///VencordPatcher:5:3339
    at Set.forEach (<anonymous>)
    at ye.markAsChanged (file:///VencordPatcher:5:3328)
    at ye.setData (file:///VencordPatcher:5:2713)
    at file:///VencordPatcher:5:4686
    at Session.<anonymous> (node:electron/js2c/browser_init:2:107040)
    at Session.emit (node:events:519:28) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/agon/Library/Application Support/Vencord/settings/settings.json'
}
Failed to write renderer settings Error: EACCES: permission denied, open '/Users/agon/Library/Application Support/Vencord/settings/settings.json'
    at writeFileSync (node:fs:2425:20)
    at file:///VencordPatcher:5:4473
    at file:///VencordPatcher:5:3339
    at Set.forEach (<anonymous>)
    at ye.markAsChanged (file:///VencordPatcher:5:3328)
    at ye.setData (file:///VencordPatcher:5:2713)
    at file:///VencordPatcher:5:4686
    at Session.<anonymous> (node:electron/js2c/browser_init:2:107040)
    at Session.emit (node:events:519:28) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/agon/Library/Application Support/Vencord/settings/settings.json'
}
Failed to write renderer settings Error: EACCES: permission denied, open '/Users/agon/Library/Application Support/Vencord/settings/settings.json'
    at writeFileSync (node:fs:2425:20)
    at file:///VencordPatcher:5:4473
    at file:///VencordPatcher:5:3339
    at Set.forEach (<anonymous>)
    at ye.markAsChanged (file:///VencordPatcher:5:3328)
    at ye.setData (file:///VencordPatcher:5:2713)
    at file:///VencordPatcher:5:4686
    at Session.<anonymous> (node:electron/js2c/browser_init:2:107040)
    at Session.emit (node:events:519:28) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/agon/Library/Application Support/Vencord/settings/settings.json'
}
(node:25420) UnhandledPromiseRejectionWarning: Error: An object could not be cloned.
    at IpcRendererInternal.send (node:electron/js2c/renderer_init:2:12189)
    at IpcRendererInternal.<anonymous> (node:electron/js2c/renderer_init:2:11828)
(Use `Discord --trace-warnings ...` to show where the warning was created)
(node:25420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
ipcMain.on(IPCEvents.APP_ASYNC_INDEX_TSX_LOADED) false false
```

**Comment by 4evy** [comment]
@Random-Scientist Try latest again and could you `rm -rf ~/Library/Application\ Support/discord/` and start discord from the cli (after you rebuild on latest)?

**Comment by Random-Scientist** [comment]
Same error and failure to load

**Comment by 4evy** [comment]
Sorry for the delay, I've been traveling. Can you test the latest commit?

**Comment by Random-Scientist** [comment]
Thanks for all the work, it's working now on latest nixpkgs :)
